name: Build and deploy WAR app to Azure Web App - amzon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build WAR using Maven
        run: mvn clean install

      - name: List WAR files for verification
        run: ls -lh ${GITHUB_WORKSPACE}/Amazon-Core/target

      - name: Upload WAR artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Amazon-Core/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app

      - name: List downloaded files for verification
        run: ls -lh java-app

      - name: Deploy WAR to Azure Web App using publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amzon'  # Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: java-app/*.war
